repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-yaml
      exclude: '^\.venv/'
    - id: end-of-file-fixer
      exclude: '^\.venv/'
    - id: trailing-whitespace
      exclude: '^\.venv/'
